name: Run Design and Image Generation Engine

on:
  push:
    branches:
      - main

jobs:
  run_engine:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Execute engine.ts
      run: npm run run-engine
      
    - name: Upload generated PDF
      uses: actions/upload-artifact@v2
      with:
        name: generated-design-pdf
        path: path_to_your_pdf/*.pdf

